[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1440x900x24
autorestart=true
priority=10

[program:openbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":1",HOME="/home/volatile"
autorestart=true
priority=20

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -listen localhost -xkb
environment=DISPLAY=":1",HOME="/home/volatile"
autorestart=true
priority=30

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --listen 6080 --vnc localhost:5900
autorestart=true
priority=40

[program:firefox]
command=/opt/volatile/launch_firefox.sh
environment=DISPLAY=":1",HOME="/home/volatile",DOWNLOAD_DIR="/home/volatile/downloads"
autorestart=true
priority=50

