version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      VW_FRONTEND_ORIGIN: http://localhost:5173
      VW_ATTACHED_CONTAINER_NAME: fc9cebd2adf757ae2135d9299b30fb0fe051db52c486c1f9b72e5d99779f46c2
      VW_BROWSER_URL: http://localhost:3000
      VW_DOWNLOAD_DIR: /config/downloads
      VW_END_SESSION_STOPS_CONTAINER: "false"
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
